/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package io.gearpump.examples.iotdemo;

import org.openimaj.image.DisplayUtilities;
import org.openimaj.image.ImageUtilities;
import org.openimaj.image.MBFImage;
import org.openimaj.video.VideoDisplay;
import org.openimaj.video.capture.VideoCapture;
import org.openimaj.video.capture.VideoCaptureException;

import java.awt.image.BufferedImage;

/**
 *
 * @author huafengw
 */
public class CaptruingFrame extends javax.swing.JFrame {
  private AnalyzeTask analyzeTask;
  private VideoCapture videoCapture;
  private VideoDisplay videoDisplay;

  /** Creates new form CaptruingFrame */
  public CaptruingFrame(AnalyzeTask analyzeTask) throws VideoCaptureException {
    initComponents();
    this.analyzeTask = analyzeTask;
    this.videoCapture = new VideoCapture(320, 240);
    this.videoDisplay = VideoDisplay.createVideoDisplay(this.videoCapture, this.capturingPanle);
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    userName = new javax.swing.JTextField();
    capture_button = new javax.swing.JButton();
    restart_button = new javax.swing.JButton();
    warning_label = new javax.swing.JLabel();
    jPanel1 = new javax.swing.JPanel();
    capturingPanle = new javax.swing.JPanel();
    detectionPanel = new javax.swing.JPanel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowClosed(java.awt.event.WindowEvent evt) {
        formWindowClosed(evt);
      }
    });
    jLabel1.setText("Captrued Video");

    jLabel2.setText("Search Result");

    jLabel3.setText("Name");

    userName.setToolTipText("");

    capture_button.setText("Capture");
    capture_button.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        capture_buttonActionPerformed(evt);
      }
    });

    restart_button.setText("Restart");
    restart_button.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        restart_buttonActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout capturingPanleLayout = new javax.swing.GroupLayout(capturingPanle);
    capturingPanle.setLayout(capturingPanleLayout);
    capturingPanleLayout.setHorizontalGroup(
      capturingPanleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 0, Short.MAX_VALUE)
    );
    capturingPanleLayout.setVerticalGroup(
      capturingPanleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 0, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(capturingPanle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(capturingPanle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout detectionPanelLayout = new javax.swing.GroupLayout(detectionPanel);
    detectionPanel.setLayout(detectionPanelLayout);
    detectionPanelLayout.setHorizontalGroup(
      detectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 0, Short.MAX_VALUE)
    );
    detectionPanelLayout.setVerticalGroup(
      detectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 240, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
          .addContainerGap()
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(warning_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
              .addComponent(restart_button, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
              .addComponent(capture_button, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
              .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGap(18, 18, 18)
              .addComponent(userName))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGap(29, 29, 29)
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
              .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGap(0, 184, Short.MAX_VALUE))
            .addComponent(detectionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
          .addGap(4, 4, 4)
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
            .addComponent(detectionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(capture_button)
            .addComponent(restart_button))
          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
          .addComponent(warning_label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addContainerGap(20, Short.MAX_VALUE))
    );

    capture_button.getAccessibleContext().setAccessibleDescription("");

    pack();
  }// </editor-fold>

  private void capture_buttonActionPerformed(java.awt.event.ActionEvent evt) {
    MBFImage image = this.videoCapture.getCurrentFrame();
    BufferedImage bufferedImage = ImageUtilities.createBufferedImageForDisplay(image);
    this.videoCapture.stopCapture();
    DisplayUtilities.ImageComponent c;
    if (detectionPanel.getComponentCount() > 0 && detectionPanel.getComponent(0) instanceof DisplayUtilities.ImageComponent) {
      c = (DisplayUtilities.ImageComponent)detectionPanel.getComponent(0);
      c.setImage(bufferedImage);
      c.setOriginalImage(image);
    } else {
      detectionPanel.removeAll();
      c = new DisplayUtilities.ImageComponent(bufferedImage);
      c.setOriginalImage(image);
      this.detectionPanel.add(c);
    }
    c.setVisible(true);
  }

  private void restart_buttonActionPerformed(java.awt.event.ActionEvent evt) {
    this.videoCapture.close();
    this.videoDisplay.close();
    this.capturingPanle.removeAll();
    try {
      this.videoCapture = new VideoCapture(320, 240);
    } catch (VideoCaptureException e) {
      e.printStackTrace();
    }
    this.videoDisplay = VideoDisplay.createVideoDisplay(this.videoCapture, this.capturingPanle);

    if (detectionPanel.getComponentCount() > 0 && detectionPanel.getComponent(0) instanceof DisplayUtilities.ImageComponent) {
      DisplayUtilities.ImageComponent c = (DisplayUtilities.ImageComponent)detectionPanel.getComponent(0);
      c.setVisible(false);
    }
  }

  private void formWindowClosed(java.awt.event.WindowEvent evt) {
    this.videoCapture.close();
    this.videoDisplay.close();
  }

  // Variables declaration - do not modify
  private javax.swing.JButton capture_button;
  private javax.swing.JPanel capturingPanle;
  private javax.swing.JPanel detectionPanel;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JButton restart_button;
  private javax.swing.JTextField userName;
  private javax.swing.JLabel warning_label;
  // End of variables declaration

}

